import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://wms.godamwale.com/login');
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('Demo1@godamwale.com');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').fill('Dodamwale');
  await page.locator('svg').click();
  await page.locator('nz-input-group').getByPlaceholder('Enter').click();
  await page.locator('nz-input-group').getByPlaceholder('Enter').fill('Godamwale@1234');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.locator('a').filter({ hasText: 'Products' }).first().click();
  await page.getByRole('button', { name: '+ PRODUCT' }).click();
  await page.getByPlaceholder('(E.g. Puma Shoes)').click();
  await page.getByPlaceholder('(E.g. Puma Shoes)').fill('HP');
  await page.getByPlaceholder('(E.g. PUM-BLK-12)').click();
  await page.getByPlaceholder('(E.g. PUM-BLK-12)').fill('H0');
  await page.locator('#formly_16_select_stockActivity_2').getByRole('textbox').click();
  await page.getByText('Sellable').click();
  await page.locator('#formly_16_add-autocomplete_categoryId_8').getByRole('textbox').click();
  await page.getByText('Category927').click();
  await page.locator('nz-select-top-control').filter({ hasText: 'Select Supplier' }).click();
  await page.getByTitle('Vikas ', { exact: true }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.locator('#formly_48_select_packagingType_0').getByRole('textbox').click();
  await page.getByText('Single').click();
  await page.locator('nz-select-top-control').filter({ hasText: 'Storage Warehouse' }).click();
  await page.locator('#formly_48_select_warehouseIds_3').getByRole('textbox').fill('ShriRam');
  await page.getByText('ShriRam WH').click();
  await page.locator('#formly_48_select_dispatchMethod_4').getByRole('textbox').click();
  await page.getByText('LIFO').click();
  await page.locator('#formly_48_select_identificationType_5').getByRole('textbox').click();
  await page.getByTitle('all').click();
  await page.locator('#formly_48_select_gstPercentage_9').getByRole('textbox').click();
  await page.getByText('0%').click();
  await page.getByPlaceholder('Search HSN code here, Enter').click();
  await page.getByPlaceholder('Search HSN code here, Enter').fill('780199');
  await page.getByRole('button', { name: 'ADD PRODUCT' }).click();
});