import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://wms.godamwale.com/');
  await page.goto('https://wms.godamwale.com/login');
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('demo@godamwale.com');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').fill('Godamwale@1234');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').press('ArrowLeft');
  await page.locator('input[type="text"]').press('ArrowLeft');
  await page.locator('input[type="text"]').press('ArrowLeft');
  await page.locator('input[type="text"]').press('ArrowLeft');
  await page.locator('input[type="text"]').press('ArrowLeft');
  await page.locator('input[type="text"]').press('ArrowLeft');
  await page.locator('input[type="text"]').press('ArrowLeft');
  await page.locator('input[type="text"]').press('ArrowLeft');
  await page.locator('input[type="text"]').press('ArrowLeft');
  await page.locator('input[type="text"]').press('ArrowLeft');
  await page.locator('input[type="text"]').press('ArrowRight');
  await page.locator('input[type="text"]').press('ArrowRight');
  await page.locator('input[type="text"]').press('ArrowRight');
  await page.locator('input[type="text"]').press('ArrowRight');
  await page.locator('input[type="text"]').fill('demo1@godamwale.com');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.locator('a').filter({ hasText: 'Sales' }).first().click();
  await page.getByRole('button', { name: '+ SALES ORDER' }).click();
  await page.getByText('Gitanjali WH').click();
  await page.getByText('ShriRam WH').click();
  await page.locator('nz-form-item').filter({ hasText: 'Customer Name Select Customer' }).getByRole('textbox').click();
  await page.getByText('Priya :: priya2@gmail.com').click();
  await page.getByPlaceholder('Ref. No.').click();
  await page.getByPlaceholder('Ref. No.').fill('58585');
  await page.getByLabel('Same as Billing Address').check();
  await page.getByLabel('Same as Billing Address').press('Shift+H');
  await page.getByLabel('Same as Billing Address').press('Shift+H');
  await page.getByPlaceholder('Type Product name to search a').click();
  await page.getByPlaceholder('Type Product name to search a').fill('HP');
  await page.getByText('HP').click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('1');
  await page.getByRole('tab', { name: 'Transport' }).click();
  await page.getByRole('button', { name: 'CONFIRM' }).click();
  await page.getByRole('button', { name: 'SAVE ORDER AS DRAFT' }).click();
  await page.getByRole('button', { name: '2666' }).click();
  await page.getByRole('button', { name: 'FINALIZE' }).click();
  await page.getByRole('button', { name: '2666' }).click();
  await page.getByRole('button', { name: 'Refresh' }).click();
});